# Site settings
title: PHWashResources
# Build settings
markdown: kramdown

sass:
    style: :compressed

collections:
    pillars:
        output: true
        permalink: /phats/:path/
    generalwash:
        output: true