# Site settings
title: PHWashResources
# Build settings
#url: "www.phwashresources.com" # the base hostname & protocol for your site
markdown: kramdown

sass:
    style: :compressed

collections:
    pillars:
        output: true
        permalink: /phats/:path/
    generalwash:
        output: true