- title: Learn
  img: /images/services/learn.jpg
  icon: /images/services-icon/learn.svg
  class: pull-left
  description: "Visit our WaSH resources knowledge management catalog to learn what works in the Philippines and around the world."

- title: Implement
  img: /images/services/implement.jpg
  icon: /images/services-icon/implement.svg
  class: pull-right
  description: "Philippines Approach to Total Sanitation (PhATS) is the national recovery and development strategy to promote universal access to improved sanitation and hygiene behavior. Changing social practices and building resilience in the Philippines begins by eliminating open defecation."

- title: Connect
  img: /images/services/connect.jpg
  icon: /images/services-icon/connect.svg
  class: pull-left
  description: "Start a conversation, contact Philippines WaSH Resources or join our mailing list for updates."